"use client";

import Link from "next/link";
import { addDoc, collection, serverTimestamp, Timestamp } from "firebase/firestore";
import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { EmailVerificationNotice } from "@/components/email-verification-notice";
import { db } from "@/lib/firebase";

export default function InviteTeamMemberPage() {
  const router = useRouter(); const { user, profile, isLoading, isProfileLoading } = useAuth();
  const [email, setEmail] = useState(""); const [role, setRole] = useState("site_engineer"); const [link, setLink] = useState(""); const [emailStatus, setEmailStatus] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!isLoading && !user) router.replace("/login"); if (!isProfileLoading && profile && profile.role !== "director") router.replace("/dashboard"); }, [isLoading, isProfileLoading, profile, router, user]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!profile || !email.trim() || !user) return; if (!user.emailVerified) return setError("Verify your Director email before sending an invitation."); setSaving(true); setError(""); setEmailStatus(""); try { const invitedEmail = email.trim().toLowerCase(); const invite = await addDoc(collection(db, "companies", profile.companyId, "invites"), { email: invitedEmail, role, companyName: profile.companyName, createdAt: serverTimestamp(), expiresAt: Timestamp.fromDate(new Date(Date.now() + 7 * 24 * 60 * 60 * 1000)), active: true }); const inviteLink = `${window.location.origin}/join?company=${profile.companyId}&invite=${invite.id}&companyName=${encodeURIComponent(profile.companyName)}&email=${encodeURIComponent(invitedEmail)}`; setLink(inviteLink); const idToken = await user.getIdToken(); const response = await fetch("/api/team-invite", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${idToken}` }, body: JSON.stringify({ email: invitedEmail, companyId: profile.companyId, inviteId: invite.id }) }); setEmailStatus(response.ok ? `Invitation email sent to ${invitedEmail}. It expires in 7 days.` : "Invitation created, but the email could not be sent. Copy the link below and send it manually."); } catch { setError("We could not create this invitation. Publish the invitation rule, then try again."); } finally { setSaving(false); } };
  if (isLoading || isProfileLoading || !user || !profile || profile.role !== "director") return <main className="auth-loading">Opening invitations…</main>;
  return <main className="report-page"><div className="report-content"><Link className="back-link" href="/team">← Back to team</Link><section className="report-card"><p className="eyebrow">Company administration</p><h1>Invite a team member</h1><p className="report-intro">Send a private invitation link directly to the person&apos;s work email. They will confirm the company name and create their own password.</p><EmailVerificationNotice /><form className="report-form" onSubmit={submit}><label className="report-labour-field">Work email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required /></label><label className="report-labour-field">Role<select value={role} onChange={(event) => setRole(event.target.value)}><option value="site_engineer">Site Engineer</option><option value="project_manager">Project Manager</option><option value="quantity_surveyor">Quantity Surveyor</option></select></label>{error && <p className="form-error">{error}</p>}<button disabled={saving || !user.emailVerified}>{saving ? "Sending invitation…" : "Send invitation"}</button></form>{link && <section className="report-section"><h2>Invitation ready</h2>{emailStatus && <p className={emailStatus.startsWith("Invitation email sent") ? "form-success" : "form-error"}>{emailStatus}</p>}<input readOnly value={link} onFocus={(event) => event.currentTarget.select()} /><p className="field-hint">Keep this as a backup only. The invitee should receive the link at {email.trim().toLowerCase()}.</p></section>}</section></div></main>;
}
