"use client";

import Link from "next/link";
import { addDoc, collection, onSnapshot, serverTimestamp } from "firebase/firestore";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import type { BoqItem, Variation } from "@engplatform2/shared-types";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";
import { formatNaira } from "@/lib/dashboard-data";
import { useProjects } from "@/hooks/use-projects";
import { canGenerateValuation } from "@/lib/permissions";

const today = () => new Date().toISOString().slice(0, 10);

export default function NewValuationPage() {
  const params = useParams<{ projectId: string }>(); const projectId = params.projectId; const router = useRouter();
  const { user, profile, isLoading, isProfileLoading } = useAuth(); const { projects, isLoading: projectsLoading } = useProjects(profile?.companyId);
  const project = projects.find((item) => item.id === projectId); const [items, setItems] = useState<BoqItem[]>([]); const [variations, setVariations] = useState<Variation[]>([]);
  const [certificateNumber, setCertificateNumber] = useState(""); const [valuationDate, setValuationDate] = useState(today); const [retentionRate, setRetentionRate] = useState("5"); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!isLoading && !user) router.replace("/login"); if (!isProfileLoading && user && !profile) router.replace("/onboarding"); }, [isLoading, isProfileLoading, profile, router, user]);
  useEffect(() => { if (!profile) return; return onSnapshot(collection(db, "companies", profile.companyId, "projects", projectId, "boqItems"), (snapshot) => setItems(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as BoqItem))); }, [profile, projectId]);
  useEffect(() => { if (!profile) return; return onSnapshot(collection(db, "companies", profile.companyId, "projects", projectId, "variations"), (snapshot) => setVariations(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as Variation))); }, [profile, projectId]);
  const totals = useMemo(() => { const completedBoqValue = items.reduce((total, item) => total + item.cumulativeQuantityCompleted * item.rate, 0); const approvedVariationValue = variations.filter((item) => item.status === "approved").reduce((total, item) => total + item.estimatedValue, 0); const grossValue = completedBoqValue + approvedVariationValue; const rate = Number(retentionRate) || 0; const retentionAmount = grossValue * rate / 100; return { completedBoqValue, approvedVariationValue, grossValue, retentionAmount, netAmountDue: grossValue - retentionAmount }; }, [items, retentionRate, variations]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!profile || !user) return; const rate = Number(retentionRate); if (!certificateNumber.trim() || !Number.isFinite(rate) || rate < 0 || rate > 100) return setError("Enter a certificate number and a retention rate between 0 and 100."); setSaving(true); setError(""); try { await addDoc(collection(db, "companies", profile.companyId, "projects", projectId, "valuations"), { projectId, certificateNumber: certificateNumber.trim(), valuationDate, ...totals, retentionRate: rate, status: "issued", createdBy: user.uid, createdAt: serverTimestamp() }); await addDoc(collection(db, "companies", profile.companyId, "projects", projectId, "activityLog"), { action: "valuation_issued", summary: `Valuation ${certificateNumber.trim()} was issued.`, actorName: profile.name, createdAt: serverTimestamp() }); router.replace(`/projects/${projectId}`); } catch { setError("We could not issue this valuation. Check the Firestore rules and try again."); setSaving(false); } };
  if (isLoading || isProfileLoading || projectsLoading || !user || !profile) return <main className="auth-loading">Preparing valuation…</main>; if (!project) return <main className="auth-loading">Project not found. <Link href="/">Return to dashboard</Link></main>; if (!canGenerateValuation(profile.role)) return <main className="auth-loading">Your role cannot create valuations. <Link href={`/projects/${projectId}`}>Return to project</Link></main>;
  return <main className="report-page"><div className="report-content"><Link className="back-link" href={`/projects/${projectId}`}>← Back to {project.name}</Link><section className="report-card"><p className="eyebrow">Payment certificate</p><h1>Create valuation</h1><p className="report-intro">This certificate uses the current completed BOQ value and approved variations.</p><form className="report-form" onSubmit={submit}><section className="report-section"><div className="boq-number-fields"><label className="report-labour-field">Certificate number<input value={certificateNumber} onChange={(event) => setCertificateNumber(event.target.value)} placeholder="e.g. IPC-001" required /></label><label className="report-labour-field">Valuation date<input type="date" value={valuationDate} onChange={(event) => setValuationDate(event.target.value)} required /></label></div><label className="report-labour-field">Retention rate (%)<input inputMode="decimal" value={retentionRate} onChange={(event) => setRetentionRate(event.target.value)} required /></label></section><section className="valuation-breakdown"><p><span>Completed BOQ work</span><strong>{formatNaira(totals.completedBoqValue)}</strong></p><p><span>Approved variations</span><strong>{formatNaira(totals.approvedVariationValue)}</strong></p><p><span>Gross certified value</span><strong>{formatNaira(totals.grossValue)}</strong></p><p><span>Retention</span><strong>-{formatNaira(totals.retentionAmount)}</strong></p><p className="valuation-net"><span>Net amount due</span><strong>{formatNaira(totals.netAmountDue)}</strong></p></section>{error && <p className="form-error">{error}</p>}<div className="report-submit-row"><p className="report-intro">Issuing stores a permanent snapshot of these values.</p><button disabled={saving}>{saving ? "Issuing certificate…" : "Issue valuation"}</button></div></form></section></div></main>;
}
