"use client";

import { createUserWithEmailAndPassword, sendPasswordResetEmail, signInWithEmailAndPassword } from "firebase/auth";
import { doc, getDoc, serverTimestamp, writeBatch } from "firebase/firestore";
import { FormEvent, Suspense, useState } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { auth, db } from "@/lib/firebase";

function JoinForm() {
  const params = useSearchParams(); const router = useRouter(); const companyId = params.get("company") ?? ""; const inviteId = params.get("invite") ?? ""; const invitedCompanyName = params.get("companyName") ?? ""; const invitedEmail = params.get("email") ?? "";
  const { refreshProfile } = useAuth();
  const [name, setName] = useState(""); const [companyName, setCompanyName] = useState(invitedCompanyName); const [email, setEmail] = useState(invitedEmail); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [accountExists, setAccountExists] = useState(false); const [saving, setSaving] = useState(false);
  const resetPassword = async () => { if (!email.trim()) return setError("Enter the invited work email first, then select Reset password."); setSaving(true); setError(""); setNotice(""); try { await sendPasswordResetEmail(auth, email.trim().toLowerCase()); setNotice("Password reset email sent. Set a new password, then return to this invitation link and use it to join the workspace."); } catch { setError("We could not send a reset email. Check that this is the invited email address and try again."); } finally { setSaving(false); } };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!companyId || !inviteId) return setError("This invitation link is incomplete. Ask your Director for a new link."); setSaving(true); setError(""); setNotice(""); setAccountExists(false); try { let credential; try { credential = await createUserWithEmailAndPassword(auth, email.trim(), password); } catch (authError) { if ((authError as { code?: string }).code !== "auth/email-already-in-use") throw authError; try { credential = await signInWithEmailAndPassword(auth, email.trim(), password); } catch { setAccountExists(true); throw new Error("existing-account"); } } const inviteRef = doc(db, "companies", companyId, "invites", inviteId); const invite = await getDoc(inviteRef); const expectedCompanyName = String(invite.data()?.companyName ?? "").trim(); if (!invite.exists() || !invite.data().active || String(invite.data().email).toLowerCase() !== email.trim().toLowerCase() || (expectedCompanyName && expectedCompanyName.toLowerCase() !== companyName.trim().toLowerCase())) throw new Error("invalid-invite"); const batch = writeBatch(db); batch.set(doc(db, "companies", companyId, "users", credential.user.uid), { companyId, name: name.trim(), email: email.trim().toLowerCase(), role: invite.data().role, inviteId, assignedProjectIds: [], active: true, createdAt: serverTimestamp() }); batch.set(doc(db, "userIndex", credential.user.uid), { companyId, createdAt: serverTimestamp() }); batch.update(inviteRef, { active: false, acceptedBy: credential.user.uid, acceptedAt: serverTimestamp() }); await batch.commit(); await refreshProfile(); router.replace("/dashboard"); } catch (caughtError) { const message = caughtError instanceof Error ? caughtError.message : ""; if (message === "existing-account") setError("This email already has an account. Use the password chosen on the first attempt, or reset it below."); else if (message === "invalid-invite") setError("This invitation is no longer active, or the company name and email do not match the invitation. Ask the Director to create a new invitation."); else setError("We could not join the workspace yet. Confirm that you used the invited email, then try again."); } finally { setSaving(false); } };
  return <main className="onboarding-page"><section className="onboarding-card"><p className="eyebrow">Company invitation</p><h1>Join your workspace</h1><p>Confirm your company details, then create your own secure sign-in.</p><form onSubmit={submit}><label>Your name<input value={name} onChange={(event) => setName(event.target.value)} required /></label><label>Company name<input value={companyName} onChange={(event) => setCompanyName(event.target.value)} placeholder="e.g. BuildCore" required />{invitedCompanyName && <span className="field-hint">This has been filled from your invitation. Please leave it unchanged.</span>}</label><label>Work email<input type="email" value={email} onChange={(event) => setEmail(event.target.value)} required />{invitedEmail && <span className="field-hint">This has been filled from your invitation. Please leave it unchanged.</span>}</label><label>{accountExists ? "Your existing password" : "Create password"}<input type="password" value={password} onChange={(event) => setPassword(event.target.value)} minLength={6} required /></label>{error && <p className="form-error">{error}</p>}{notice && <p className="form-success">{notice}</p>}{accountExists && <button className="secondary compact-action" type="button" disabled={saving} onClick={() => void resetPassword()}>Reset password by email</button>}<button disabled={saving}>{saving ? "Joining workspace…" : "Create account and join"}</button></form></section></main>;
}

export default function JoinPage() {
  return <Suspense fallback={<main className="onboarding-page"><section className="onboarding-card"><p>Loading invitation…</p></section></main>}><JoinForm /></Suspense>;
}
