"use client";

import Link from "next/link";
import { doc, updateDoc } from "firebase/firestore";
import { FormEvent, useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { useAuth } from "@/components/auth-provider";
import { db } from "@/lib/firebase";
import { useProjects } from "@/hooks/use-projects";

export default function ProjectSettingsPage() {
  const params = useParams<{ projectId: string }>(); const projectId = params.projectId; const router = useRouter(); const { user, profile, isLoading, isProfileLoading } = useAuth(); const { projects, isLoading: projectsLoading } = useProjects(profile?.companyId); const project = projects.find((item) => item.id === projectId);
  const [name, setName] = useState(""); const [clientName, setClientName] = useState(""); const [location, setLocation] = useState(""); const [startDate, setStartDate] = useState(""); const [endDate, setEndDate] = useState(""); const [status, setStatus] = useState("active"); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  useEffect(() => { if (!isLoading && !user) router.replace("/login"); if (!isProfileLoading && user && !profile) router.replace("/onboarding"); }, [isLoading, isProfileLoading, profile, router, user]);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!profile || !project) return; const nextName = name || project.name; const nextClientName = clientName || project.clientName; const nextLocation = location || project.location; const nextStartDate = startDate || project.startDate; const nextEndDate = endDate || project.endDate; const nextStatus = status || project.status; if (nextEndDate < nextStartDate) return setError("The planned end date must be after the start date."); setSaving(true); setError(""); try { await updateDoc(doc(db, "companies", profile.companyId, "projects", projectId), { name: nextName.trim(), clientName: nextClientName.trim(), location: nextLocation.trim(), startDate: nextStartDate, endDate: nextEndDate, status: nextStatus }); router.replace(`/projects/${projectId}`); } catch { setError("We could not update this project. Please try again."); setSaving(false); } };
  if (isLoading || isProfileLoading || projectsLoading || !user || !profile) return <main className="auth-loading">Opening project settings…</main>; if (!project) return <main className="auth-loading">Project not found. <Link href="/">Return to dashboard</Link></main>;
  return <main className="report-page"><div className="report-content"><Link className="back-link" href={`/projects/${projectId}`}>← Back to {project.name}</Link><section className="report-card"><p className="eyebrow">Project management</p><h1>Project settings</h1><p className="report-intro">Keep the client, location, programme dates, and current status accurate.</p><form className="report-form" onSubmit={submit}><section className="report-section"><label className="report-labour-field">Project name<input value={name || project.name} onChange={(event) => setName(event.target.value)} required /></label><label className="report-labour-field">Client name<input value={clientName || project.clientName} onChange={(event) => setClientName(event.target.value)} required /></label><label className="report-labour-field">Location<input value={location || project.location} onChange={(event) => setLocation(event.target.value)} required /></label></section><section className="report-section"><div className="boq-number-fields"><label className="report-labour-field">Start date<input type="date" value={startDate || project.startDate} onChange={(event) => setStartDate(event.target.value)} required /></label><label className="report-labour-field">Planned end date<input type="date" value={endDate || project.endDate} onChange={(event) => setEndDate(event.target.value)} required /></label></div><label className="report-labour-field">Project status<select value={status || project.status} onChange={(event) => setStatus(event.target.value)}><option value="active">Active</option><option value="on_hold">On hold</option><option value="completed">Completed</option></select></label></section>{error && <p className="form-error">{error}</p>}<div className="report-submit-row"><p className="report-intro">Only directors can change project settings.</p><button disabled={saving}>{saving ? "Saving changes…" : "Save changes"}</button></div></form></section></div></main>;
}
